name: Main

on:
  push:
    branches:
      main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: rustup target add x86_64-unknown-linux-musl && cargo build --release --verbose
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            theme.db
            target/release/theme_engine
          token: ${{ secrets.TOKEN }}
